name: Deploy Release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy release branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Deploy to local repo
      - name: Deploy to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: addons/FracturalSceneManagement
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Zip release
        run: |
          mkdir release
          mv addons/FracturalCommons addons/FracturalSceneManagement release

      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: release
